export const sortedKeys = {
    "action": ["name"],
    "actionOverrides": ["actionName"],
    "alerts": ["fullName"],
    "applicationVisibilities": ["application"],
    "appMenuItems": ["name"],
    "approver": ["name"],
    "appSettings": ["connectedAppName"],
    "categoryGroupVisibilities": ["dataCategoryGroup"],
    "classAccesses": ["apexClass"],
    "componentInstanceProperties": ["name"],
    "customMetadataTypeAccesses": ["name"],
    "customSettingAccesses": ["name"],
    "duplicateRuleMatchRules": ["matchingRule"],
    "entitiesAndFields": ["entityName", "fieldName"],
    "fieldPermissions": ["field"],
    "fieldUpdates": ["fullName"],
    "filters": ["field"],
    "layoutAssignments": ["layout"],
    "managedContentNodeTypes": ["nodeName"],
    "mappingFields": ["inputField"],
    "matchingRuleItems": ["fieldName"],
    "matchingRules": ["fullName"],
    "notificationTypeSettings": ["notificationType"],
    "objectMapping": ["outputObject"],
    "objectPermissions": ["object"],
    "pageAccesses": ["apexPage"],
    "recipients": ["recipient"],
    "recordTypeVisibilities": ["tab"],
    "rules": ["fullName"],
    "tabVisibilities": ["name"],
    "userPermissions": ["name"],
    "values": ["field"],
    "version": ["number"],
};

export const unsortedKeys = [
    "assignmentRule",
    "FlexiPage",
    "GlobalValueSet",
    "Layout",
    "lookupFilter",
    "picklistValues",
    "sections",
    "StandardValueSet",
    "valueSetDefinition",
];
