name: Deploy VS Code Extension

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Build Extension
          run: |
            npm ci
            npm run build